app_name: "Mentee Mentor"

default_host: <%= ENV['DEFAULT_HOST'] %>

ssl:
  ca_path: '/etc/ssl/certs'
  ca_file:

# Omniauth authentication settings.Third party application's key and secret.
omniauth:
  facebook:
    key: <%= ENV['FACEBOOK_KEY'] %>
    secret: <%= ENV['FACEBOOK_SECRET'] %>

  linkedin:
    key: <%= ENV['LINKEDIN_KEY'] %>
    secret: <%= ENV['LINKEDIN_SECRET'] %>

# Mail settings.
mail:
  address: <%= ENV['MAIL_ADDRESS'] %>
  port: <%= ENV['MAIL_PORT'] %>
  domain: <%= ENV['MAIL_DOMAIN'] %>
  user_name: <%= ENV['MAIL_USER_NAME'] %>
  password: <%= ENV['MAIL_PASSWORD'] %>
  from: 'no-reply@mentor-mentee.com'

# This is for use only when Gmail SMTP config is unsupported on platforms
# this application is deployed to.
# On Heroku, esp. only SendGrid Email settings are supported which is licensed.
# So for features relying on Mail config, an alternate approach should be devised
# and implemented and based on the value of this variable the appropriate
# implementation should be invoked.
mail_settings_available: <%= ENV['MAIL_SETTINGS_AVAILABLE'] %>

